package server

import db.{
  PokemonDB,
  UserDB,
  CapturedPokemonDB,
  GenPokemonDB,
  ItemDB,
  OwnedItemDB,
  GenItemDB
}
import common.ItemType
import ext.MyFuture._

object Main {
  def main(args: Array[String]) {
    UserDB add_user ("test", "test") run (1);
    pokemon_list foreach ((x:String) => PokemonDB add_pokemon x run (1));
    item_list    foreach ((x:(String,ItemType.Value)) => ItemDB add_item (x._1,ItemType(x._2)) run (1));
    OwnedItemDB add_owned (1L,1L,20L) run (1);
    GenItemDB   add_item  (1L,1L,1L) run (1);

    ServerFactory[ServerActor,DefaultActor] ("server")
  }

  def item_list =
    List(
      ("Pokeball",ItemType.BALL),
      ("Superball",ItemType.BALL),
      ("Hyperball",ItemType.BALL),
      ("Heal",ItemType.POTION),
      ("Ease",ItemType.POTION))

  def pokemon_list = List("Bulbasaur","Chikorita", "Treecko", "Turtwig",
    "Victini", "Chespin", "Rowlet", "Ivysaur", "Bayleef", "Grovyle",
    "Grotle", "Snivy", "Quilladin", "Dartrix", "Venusaur", "Meganium",
    "Sceptile", "Torterra", "Servine", "Chesnaught", "Decidueye",
    "Charmander", "Cyndaquil", "Torchic",  "Chimchar",  "Serperior",
    "Fennekin",  "Litten",  "Charmeleon",  "Quilava",  "Combusken",
    "Monferno",  "Tepig",  "Braixen",  "Torracat",  "Charizard",
    "Typhlosion",  "Blaziken",  "Infernape",  "Pignite",  "Delphox",
    "Incineroar",  "Squirtle",  "Totodile",  "Mudkip",  "Piplup",
    "Emboar",  "Froakie",  "Popplio",  "Wartortle",  "Croconaw",
    "Marshtomp",  "Prinplup",  "Oshawott",  "Frogadier",  "Brionne",
    "Blastoise",  "Feraligatr",  "Swampert",  "Empoleon",  "Dewott",
    "Greninja",  "Primarina",  "Caterpie",  "Sentret",  "Poochyena",
    "Starly",  "Samurott",  "Bunnelby",  "Pikipek",  "Metapod",
    "Furret",  "Mightyena",  "Staravia",  "Patrat",  "Diggersby",
    "Trumbeak",  "Butterfree",  "Hoothoot",  "Zigzagoon",  "Staraptor",
    "Watchog",  "Fletchling",  "Toucannon",  "Weedle",  "Noctowl",
    "Linoone",  "Bidoof",  "Lillipup",  "Fletchinder",  "Yungoos",
    "Kakuna",  "Ledyba",  "Wurmple",  "Bibarel",  "Herdier",
    "Talonflame",  "Gumshoos",  "Beedrill",  "Ledian",  "Silcoon",
    "Kricketot",  "Stoutland",  "Scatterbug",  "Grubbin",  "Pidgey",
    "Spinarak",  "Beautifly",  "Kricketune",  "Purrloin",  "Spewpa",
    "Charjabug",  "Pidgeotto",  "Ariados",  "Cascoon",  "Shinx",
    "Liepard",  "Vivillon",  "Vikavolt",  "Pidgeot",  "Crobat",
    "Dustox",  "Luxio",  "Pansage",  "Litleo",  "Crabrawler",
    "Rattata",  "Chinchou",  "Lotad",  "Luxray",  "Simisage",  "Pyroar",
    "Crabominable",  "Raticate",  "Lanturn",  "Lombre",  "Budew",
    "Pansear",  "Flabébé",  "Oricorio",  "Spearow",  "Pichu",
    "Ludicolo",  "Roserade",  "Simisear",  "Floette",  "Cutiefly",
    "Fearow",  "Cleffa",  "Seedot",  "Cranidos",  "Panpour",  "Florges",
    "Ribombee",  "Ekans",  "Igglybuff",  "Nuzleaf",  "Rampardos",
    "Simipour",  "Skiddo",  "Rockruff",  "Arbok",  "Togepi",  "Shiftry",
    "Shieldon",  "Munna",  "Gogoat",  "Lycanroc",  "Pikachu",
    "Togetic",  "Taillow",  "Bastiodon",  "Musharna",  "Wishiwashi",
    "Raichu",  "Natu",  "Swellow",  "Burmy",  "Pidove",  "Pangoro",
    "Mareanie",  "Sandshrew",  "Xatu",  "Wingull",  "Wormadam",
    "Tranquill",  "Furfrou",  "Toxapex",  "Sandslash",  "Mareep",
    "Pelipper",  "Mothim",  "Unfezant",  "Espurr",  "Mudbray",
    "Nidoran",  "Flaaffy",  "Ralts",  "Combee",  "Blitzle",  "Meowstic",
    "Mudsdale",  "Nidorina",  "Ampharos",  "Kirlia",  "Vespiquen",
    "Zebstrika",  "Honedge",  "Dewpider",  "Nidoqueen",  "Bellossom",
    "Gardevoir",  "Pachirisu",  "Roggenrola",  "Doublade",  "Araquanid",
    "Marill",  "Surskit",  "Buizel",  "Boldore",  "Aegislash",
    "Fomantis",  "Nidorino",  "Azumarill",  "Masquerain",  "Floatzel",
    "Gigalith",  "Spritzee",  "Lurantis",  "Nidoking",  "Sudowoodo",
    "Shroomish",  "Cherubi",  "Woobat",  "Aromatisse",  "Morelull",
    "Clefairy",  "Politoed",  "Breloom",  "Cherrim",  "Swoobat",
    "Swirlix",  "Shiinotic",  "Clefable",  "Hoppip",  "Slakoth",
    "Shellos",  "Drilbur",  "Slurpuff",  "Salandit",  "Vulpix",
    "Skiploom",  "Vigoroth",  "Gastrodon",  "Excadrill",  "Inkay",
    "Salazzle",  "Ninetales",  "Jumpluff",  "Ambipom",  "Audino",
    "Malamar",  "Stufful",  "Jigglypuff",  "Aipom",  "Nincada",
    "Drifloon",  "Timburr",  "Binacle",  "Bewear",  "Wigglytuff",
    "Sunkern",  "Ninjask",  "Drifblim",  "Gurdurr",  "Barbaracle",
    "Bounsweet",  "Zubat",  "Sunflora",  "Shedinja",  "Buneary",
    "Conkeldurr",  "Skrelp",  "Steenee",  "Golbat",  "Yanma",
    "Whismur",  "Lopunny",  "Tympole",  "Dragalge",  "Tsareena",
    "Oddish",  "Wooper",  "Loudred",  "Mismagius",  "Palpitoad",
    "Clauncher",  "Comfey",  "Gloom",  "Quagsire",  "Exploud",
    "Honchkrow",  "Seismitoad",  "Clawitzer",  "Oranguru",  "Vileplume",
    "Espeon",  "Makuhita",  "Glameow",  "Throh",  "Helioptile",
    "Passimian",  "Paras",  "Umbreon",  "Hariyama",  "Purugly",  "Sawk",
    "Heliolisk",  "Wimpod",  "Parasect",  "Murkrow",  "Azurill",
    "Chingling",  "Sewaddle",  "Tyrunt",  "Golisopod",  "Venonat",
    "Slowking",  "Nosepass",  "Stunky",  "Swadloon",  "Tyrantrum",
    "Sandygast",  "Venomoth",  "Misdreavus",  "Skitty",  "Skuntank",
    "Leavanny",  "Amaura",  "Palossand",  "Diglett",  "Unown",
    "Delcatty",  "Bronzor",  "Venipede",  "Aurorus",  "Pyukumuku",
    "Dugtrio",  "Wobbuffet",  "Sableye",  "Bronzong",  "Whirlipede",
    "Sylveon",  "Meowth",  "Girafarig",  "Mawile",  "Bonsly",
    "Scolipede",  "Hawlucha",  "Silvally",  "Persian",  "Pineco",
    "Aron",  "Mime Jr.",  "Cottonee",  "Dedenne",  "Minior",  "Psyduck",
    "Forretress",  "Lairon",  "Happiny",  "Whimsicott",  "Carbink",
    "Komala",  "Golduck",  "Dunsparce",  "Aggron",  "Chatot",
    "Petilil",  "Goomy",  "Turtonator",  "Mankey",  "Gligar",
    "Meditite",  "Spiritomb",  "Lilligant",  "Sliggoo",  "Togedemaru",
    "Primeape",  "Steelix",  "Medicham",  "Gible",  "Basculin",
    "Goodra",  "Mimikyu",  "Growlithe",  "Snubbull",  "Electrike",
    "Gabite",  "Sandile",  "Klefki",  "Bruxish",  "Arcanine",
    "Granbull",  "Manectric",  "Garchomp",  "Krokorok",  "Phantump",
    "Drampa",  "Poliwag",  "Qwilfish",  "Plusle",  "Munchlax",
    "Krookodile",  "Trevenant",  "Dhelmise",  "Poliwhirl",  "Scizor",
    "Minun",  "Riolu",  "Darumaka",  "Pumpkaboo",  "Jangmo-o",
    "Poliwrath",  "Shuckle",  "Volbeat",  "Lucario",  "Darmanitan",
    "Gourgeist",  "Hakamo-o",  "Abra",  "Heracross",  "Illumise",
    "Hippopotas",  "Maractus",  "Bergmite",  "Kommo-o",  "Sneasel",
    "Roselia",  "Hippowdon",  "Dwebble",  "Avalugg",  "Tapu Koko",
    "bra",  "Kadabra",  "Alakazam",  "Teddiursa",  "Gulpin",  "Skorupi",
    "Crustle",  "Noibat",  "Tapu Lele",  "Machop",  "Ursaring",
    "Swalot",  "Drapion",  "Scraggy",  "Noivern",  "Tapu Bulu",
    "Machoke",  "Slugma",  "Carvanha",  "Croagunk",  "Scrafty",
    "Xerneas",  "Tapu Fini",  "Machamp",  "Magcargo",  "Sharpedo",
    "Toxicroak",  "Sigilyph",  "Yveltal",  "Cosmog",  "Bellsprout",
    "Swinub",  "Wailmer",  "Carnivine",  "Yamask",  "Zygarde",
    "Cosmoem",  "Weepinbell",  "Piloswine",  "Wailord",  "Finneon",
    "Cofagrigus",  "Diancie",  "Solgaleo",  "Victreebel",  "Corsola",
    "Numel",  "Lumineon",  "Tirtouga",  "Hoopa",  "Lunala",
    "Tentacool",  "Remoraid",  "Camerupt",  "Mantyke",  "Carracosta",
    "Volcanion",  "Nihilego",  "Tentacruel",  "Octillery",  "Torkoal",
    "Snover",  "Archen",  "Buzzwole",  "Geodude",  "Delibird",
    "Spoink",  "Abomasnow",  "Archeops",  "Pheromosa",  "Graveler",
    "Mantine",  "Grumpig",  "Weavile",  "Trubbish",  "Xurkitree",
    "Golem",  "Skarmory",  "Spinda",  "Magnezone",  "Garbodor",
    "Celesteela",  "Ponyta",  "Houndour",  "Trapinch",  "Lickilicky",
    "Zorua",  "Kartana",  "Rapidash",  "Houndoom",  "Vibrava",
    "Rhyperior",  "Zoroark",  "Guzzlord",  "Slowpoke",  "Slowbro",
    "Kingdra",  "Flygon",  "Tangrowth",  "Minccino",  "Necrozma",
    "Slowbro",  "Phanpy",  "Cacnea",  "Electivire",  "Cinccino",
    "Magearna",  "Magnemite",  "Donphan",  "Cacturne",  "Magmortar",
    "Gothita",  "Magneton",  "Porygon",  "Swablu",  "Togekiss",
    "Gothorita",  "Farfetch'd",  "Stantler",  "Altaria",  "Yanmega",
    "Gothitelle",  "Doduo",  "Smeargle",  "Zangoose",  "Leafeon",
    "Solosis",  "Dodrio",  "Tyrogue",  "Seviper",  "Glaceon",
    "Duosion",  "Seel",  "Hitmontop",  "Lunatone",  "Gliscor",
    "Reuniclus",  "Dewgong",  "Smoochum",  "Solrock",  "Mamoswine",
    "Ducklett",  "Grimer",  "Elekid",  "Barboach",  "Porygon-Z",
    "Swanna",  "Muk",  "Magby",  "Whiscash",  "Gallade",  "Vanillite",
    "Shellder",  "Miltank",  "Corphish",  "Probopass",  "Vanillish",
    "Cloyster",  "Blissey",  "Crawdaunt",  "Dusknoir",  "Vanilluxe",
    "Gastly",  "Raikou",  "Baltoy",  "Froslass",  "Deerling",
    "Haunter",  "Entei",  "Claydol",  "Rotom",  "Sawsbuck",  "Gengar",
    "Suicune",  "Lileep",  "Uxie",  "Emolga",  "Onix",  "Larvitar",
    "Cradily",  "Mesprit",  "Karrablast",  "Drowzee",  "Pupitar",
    "Anorith",  "Azelf",  "Escavalier",  "Hypno",  "Tyranitar",
    "Armaldo",  "Dialga",  "Foongus",  "Krabby",  "Lugia",  "Feebas",
    "Palkia",  "Amoonguss",  "Kingler",  "Ho-Oh",  "Milotic",
    "Heatran",  "Frillish",  "Voltorb",  "Celebi",  "Castform",
    "Regigigas",  "Jellicent",  "Electrode",  "Kecleon",  "Giratina",
    "Alomomola",  "Exeggcute",  "Shuppet",  "Cresselia",  "Joltik",
    "Exeggutor",  "Banette",  "Phione",  "Galvantula",  "Cubone",
    "Duskull",  "Manaphy",  "Ferroseed",  "Marowak",  "Dusclops",
    "Darkrai",  "Ferrothorn",  "Hitmonlee",  "Tropius",  "Shaymin",
    "Klink",  "Hitmonchan",  "Chimecho",  "Arceus",  "Klang",
    "Lickitung",  "Absol",  "Klinklang",  "Koffing",  "Wynaut",
    "Tynamo",  "Weezing",  "Snorunt",  "Eelektrik",  "Rhyhorn",
    "Glalie",  "Eelektross",  "Rhydon",  "Spheal",  "Elgyem",
    "Chansey",  "Sealeo",  "Beheeyem",  "Tangela",  "Walrein",
    "Litwick",  "Kangaskhan",  "Clamperl",  "Lampent",  "Horsea",
    "Huntail",  "Chandelure",  "Seadra",  "Gorebyss",  "Axew",
    "Goldeen",  "Relicanth",  "Fraxure",  "Seaking",  "Luvdisc",
    "Haxorus",  "Staryu",  "Bagon",  "Cubchoo",  "Starmie",  "Shelgon",
    "Beartic",  "Mr. Mime",  "Salamence",  "Cryogonal",  "Scyther",
    "Beldum",  "Shelmet",  "Jynx",  "Metang",  "Accelgor",
    "Electabuzz",  "Metagross",  "Stunfisk",  "Magmar",  "Regirock",
    "Mienfoo",  "Pinsir",  "Regice",  "Mienshao",  "Tauros",
    "Registeel",  "Druddigon",  "Magikarp",  "Latias",  "Golett",
    "Gyarados",  "Latios",  "Golurk",  "Lapras",  "Kyogre",  "Pawniard",
    "Ditto",  "Groudon",  "Bisharp",  "Eevee",  "Rayquaza",
    "Bouffalant",  "Vaporeon",  "Jirachi",  "Rufflet",  "Jolteon",
    "Deoxys",  "Braviary",  "Flareon",  "Vullaby",  "Porygon",
    "Mandibuzz",  "Omanyte",  "Heatmor",  "Omastar",  "Durant",
    "Kabuto",  "Deino",  "Kabutops",  "Zweilous",  "Aerodactyl",
    "Hydreigon",  "Snorlax",  "Larvesta",  "Articuno",  "Volcarona",
    "Zapdos",  "Cobalion",  "Moltres",  "Terrakion",  "Dratini",
    "Virizion",  "Dragonair",  "Tornadus",  "Dragonite",  "Thundurus",
    "Mewtwo",  "Reshiram",  "Mew",  "Zekrom",  "Landorus",  "Kyurem",
    "Keldeo",  "Meloetta",  "Genesect")

}
